apiVersion: v1
kind: Service
metadata:
  name: web1
  labels:
    name: web1
    app: demo
spec:
  selector:
    name: web1
  type: NodePort
  ports:
   - port: 80
     targetPort: 5000
     protocol: TCP
